augmentation:
  magnitude: 9
  num_ops: 2
  use_randaugment: true
data:
  batch_size: 16
  img_size: 224
  num_classes: 6
loss:
  label_smoothing: 0.1
model:
  dropout_rate: 0.3
  freeze_backbone: true
  name: "google/vit-base-patch16-224-in21k"
  from_huggingface: true
  pretrained: true
optimizer:
  name: AdamW
  weight_decay: 0.01
scheduler:
  T_max: 80
  name: CosineAnnealingLR
training:
  epochs: 50
  gradient_clip: 1.0
  lr: 0.00005
  min_epochs: 20
  patience: 15
  unfreeze_epoch: 10
